Vagrant.configure(2) do |config|

  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 4
  end

  config.vm.box = "debian/stretch64"

  config.vm.define "qgis4" do |machine|
    machine.vm.hostname = "qgis4"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.verbose = true
    ansible.playbook = "playbook.yml"
    ansible.raw_arguments = Shellwords.shellsplit(ENV['ANSIBLE_ARGS']) if ENV['ANSIBLE_ARGS']
  end
end
