Vagrant.configure(2) do |config|

  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 4
  end

  config.vm.box = "debian/stretch64"

  config.vm.define "qgis4" do |machine|
    machine.vm.hostname = "qgis4"
    machine.vm.network "private_network", ip: "192.168.77.2"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.become = true
    ansible.verbose = true
    ansible.playbook = "playbook.yml"
  end
end
