FROM debian:jessie

MAINTAINER Richard Duivenvoorde <richard@duif.net>

# Use local cached debs from host (saves your bandwidth!)
# Change ip below to that of your apt-cacher-ng host
# Or comment this line out if you do not want to use caching
#ADD 71-apt-cacher-ng /etc/apt/apt.conf.d/71-apt-cacher-ng

RUN apt-get update
RUN apt-get install -y python2.7 python-pip curl python-setuptools apt-utils gettext rpl
RUN curl https://bitbucket.org/pypa/setuptools/raw/bootstrap/ez_setup.py | python
RUN curl -o /REQUIREMENTS.txt https://raw.githubusercontent.com/qgis/QGIS-Documentation/master/REQUIREMENTS.txt 
RUN pip install -r /REQUIREMENTS.txt
